### ISSUE TITLE
placeholder still shows after list added

### ISSUE THREAD

**Issue by deanshub** [icelab/draft-js-autolist-plugin#1]
when the only thing inserted to the editor is a list then the placeholder still shows which is an unwanted behavior
![](http://img.prntscr.com/img?url=http://i.imgur.com/Ir67wyn.png)

**Comment by makenosound** [comment]
@deanshub What’s the package that provides the placeholder? I think it’s a bug in that project rather than in this plugin as we definitely _want_ to show the list item when it’s empty.

**Comment by makenosound** [comment]
@deanshub FYI I opened [an issue regarding this question](https://github.com/facebook/draft-js/issues/446) on the `draft-js` project and @hellendag has elucidated the reasoning behind why the placeholder doesn’t disappear.
