### ISSUE TITLE
getEditorState is not a function

### ISSUE THREAD

**Issue by tcaer** [icelab/draft-js-autolist-plugin#11]
I get this response when I hit the enter key. What should I do?

Thanks!

**Comment by makenosound** [comment]
Unfortunately this appears to be some incompatibility between the old structure for plugins and draft-js v0.10.1. I’m pretty stretched for time at the moment, so I won’t get a chance to look at this for at least a week, sorry. You should be able to downgrade to draft-js v0.10 and have things work again.

**Comment by ZeeStorm** [comment]
This actually appears to be an error on draft-js-plugins team:
https://github.com/draft-js-plugins/draft-js-plugins/issues/736

**Comment by tcaer** [comment]
Thanks! I will close this issue now.

**Comment by nikgraf** [comment]
@makenosound unfortunately this is due a change in the core. See a longer explanation here: https://github.com/draft-js-plugins/draft-js-plugins/issues/736#issuecomment-303476088

**Comment by makenosound** [comment]
Fixed and released as v2.0.0. Thanks for the heads up @nikgraf
