### ISSUE TITLE
Ordered list on azerty keyboards doesn't work

### ISSUE THREAD

**Issue by Grsmto** [icelab/draft-js-autolist-plugin#3]
Hi,
Not a major issue but the ordered list doesn't work on azerty (french) keyboards as we need to do this keys combination to write `1.` : `Shift + 1 + .`.

Seems to be coming from the history length: https://github.com/icelab/draft-js-autolist-plugin/blob/master/src/trackCharacters.js#L26

I can submit PR if needed. Thanks.

**Comment by makenosound** [comment]
@Grsmto Oh, nice catch. Totally happy to accept a PR!
