### ISSUE TITLE
Hitting enter at end does not break out

### ISSUE THREAD

**Issue by stevensacks** [icelab/draft-js-autolist-plugin#9]
No matter what I do, I cannot get it to break out of unordered or ordered lists by hitting enter an extra time at the end. It just doesn't work.

I have other plugins but I have disabled them all and it still doesn't work.

I'm using 2.0.0-beta9 of the plugins editor. I'm on OSX.

**Comment by stevensacks** [comment]
You have to defer the setting of the editor state in the handleReturn check.

```
if (/list-item/.test(blockType) && block.getText() === '') {
    editorState = RichUtils.toggleBlockType(editorState, blockType);
    content = editorState.getCurrentContent();
    editorState = EditorState.forceSelection(editorState, content.getSelectionAfter());
    defer(() => {setEditorState(editorState)});
    return true;
}
```

**Comment by gavinwahl** [comment]
I can reproduce this issue, and the proposed fix does work.

**Comment by gavinwahl** [comment]
#8 is a better fix for this.

**Comment by makenosound** [comment]
Closed in https://github.com/icelab/draft-js-autolist-plugin/pull/8
